import { useEffect, useState } from 'react';
import { Batch, TrainingSchedule, getBatches, getTrainingSchedules, getTrainingFeedback, submitTrainingFeedback, getTrainingFeedbackSummary, TrainingFeedback, TrainingFeedbackSummary } from './api';

type User={id:number;full_name:string;email:string;role:string;institution_id?:number};
const rating=(n:number)=>[1,2,3,4,5].map(x=><option key={x} value={x}>{x} / 5</option>);

export function TrainingEvaluation({user}:{user:User}) {
  const trainee=user.role==='TRAINEE';
  const manager=['NCCT_ADMIN','INSTITUTE_ADMIN','TRAINER'].includes(user.role);
  const [batches,setBatches]=useState<Batch[]>([]); const [schedules,setSchedules]=useState<TrainingSchedule[]>([]); const [feedback,setFeedback]=useState<TrainingFeedback[]>([]); const [summary,setSummary]=useState<TrainingFeedbackSummary[]>([]); const [batchId,setBatchId]=useState(0); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
  const [form,setForm]=useState({schedule_id:0,content_rating:5,trainer_rating:5,venue_rating:5,overall_rating:5,comments:''});
  async function load(){ setLoading(true); setMessage(''); try { const b=await getBatches(); setBatches(b); const id=batchId||b[0]?.id||0; setBatchId(id); const [s,f]=await Promise.all([getTrainingSchedules(id?{batch_id:id}:undefined),getTrainingFeedback(id?{batch_id:id}:undefined)]); setSchedules(s); setFeedback(f); if(manager) setSummary(await getTrainingFeedbackSummary(id||undefined)); } catch(e:any){setMessage(e.response?.data?.detail||'Could not load training evaluation');} finally{setLoading(false);} }
  useEffect(()=>{load();},[batchId]);
  const submitted=new Set(feedback.map(x=>x.schedule_id));
  async function submit(e:React.FormEvent){e.preventDefault(); setLoading(true); setMessage(''); try{await submitTrainingFeedback({...form,schedule_id:Number(form.schedule_id),comments:form.comments||undefined});setMessage('Training feedback submitted. Thank you.');setForm(x=>({...x,schedule_id:0,comments:''}));await load();}catch(e:any){setMessage(e.response?.data?.detail||'Could not submit feedback');}finally{setLoading(false);}}
  return <div className="training-evaluation">
    <section className="panel"><div className="panel-title"><div><p className="eyebrow">TRAINING ERP • ERP-10</p><h2>Training Evaluation & Feedback</h2><p className="muted">Capture session-level feedback and turn trainee responses into actionable training insights.</p></div></div>{message&&<div className="notice">{message}</div>}{manager&&<div className="form-row" style={{marginTop:12}}><label>Batch<select value={batchId} onChange={e=>setBatchId(Number(e.target.value))}><option value={0}>All batches</option>{batches.map(b=><option key={b.id} value={b.id}>{b.batch_code}</option>)}</select></label></div>}</section>
    {trainee&&<section className="panel"><div className="panel-title"><div><h3>Submit session feedback</h3><p className="muted">Rate content, trainer, venue and your overall experience from 1 to 5.</p></div></div><form className="career-form" onSubmit={submit}><label>Training session<select value={form.schedule_id} onChange={e=>setForm({...form,schedule_id:Number(e.target.value)})} required><option value={0}>Select completed session</option>{schedules.filter(s=>!submitted.has(s.id)).map(s=><option key={s.id} value={s.id}>{s.session_date} • {s.topic} • {s.batch_code}</option>)}</select></label><div className="form-row"><label>Content quality<select value={form.content_rating} onChange={e=>setForm({...form,content_rating:Number(e.target.value)})}>{rating(form.content_rating)}</select></label><label>Trainer effectiveness<select value={form.trainer_rating} onChange={e=>setForm({...form,trainer_rating:Number(e.target.value)})}>{rating(form.trainer_rating)}</select></label></div><div className="form-row"><label>Venue / delivery<select value={form.venue_rating} onChange={e=>setForm({...form,venue_rating:Number(e.target.value)})}>{rating(form.venue_rating)}</select></label><label>Overall experience<select value={form.overall_rating} onChange={e=>setForm({...form,overall_rating:Number(e.target.value)})}>{rating(form.overall_rating)}</select></label></div><label>Comments<textarea rows={4} value={form.comments} onChange={e=>setForm({...form,comments:e.target.value})} placeholder="What should be improved or continued?"/></label><button className="primary" disabled={loading||!form.schedule_id}>Submit feedback</button></form>{!schedules.filter(s=>!submitted.has(s.id)).length&&<div className="empty" style={{marginTop:12}}>No unreviewed training sessions are available.</div>}</section>}
    {manager&&<section className="panel"><div className="panel-title"><div><h3>Session feedback summary</h3><p className="muted">Aggregated ratings from trainee feedback. No individual comments are exposed in this summary.</p></div><button className="secondary" onClick={load} disabled={loading}>Refresh</button></div><div className="application-list">{summary.map(s=><div className="application-row" key={s.schedule_id}><div><strong>{s.topic}</strong><span>{s.batch_code} • {s.session_date}</span><small>{s.responses} response{s.responses===1?'':'s'} • Content {s.average_content}/5 • Trainer {s.average_trainer}/5 • Venue {s.average_venue}/5</small></div><span className="status-badge">Overall {s.average_overall}/5</span></div>)}{!summary.length&&<div className="empty">No feedback has been submitted for the selected batch yet.</div>}</div></section>}
    {trainee&&feedback.length>0&&<section className="panel"><div className="panel-title"><div><h3>My submitted feedback</h3><p className="muted">Your previous session evaluations.</p></div></div><div className="application-list">{feedback.map(f=><div className="application-row" key={f.id}><div><strong>Session #{f.schedule_id}</strong><span>Submitted {new Date(f.submitted_at).toLocaleString()}</span>{f.comments&&<small>{f.comments}</small>}</div><span className="status-badge">{f.overall_rating}/5</span></div>)}</div></section>}
  </div>;
}
