import { useEffect, useState } from 'react';
import { api } from '../training/api';

type User={id:number;full_name:string;email:string;role:string};
type Question={id:string;question:string;options:string[]};
type Result={score:number;total_questions:number;percentage:number;level:string;completed_at:string};
type Attempt=Result&{id:number;trainee_id:number;trainee_name:string;trainee_email:string};

export function DigitalLiteracy({user}:{user:User}){
 const [questions,setQuestions]=useState<Question[]>([]); const [answers,setAnswers]=useState<Record<string,number>>({}); const [result,setResult]=useState<Result|null>(null); const [attempts,setAttempts]=useState<Attempt[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{setQuestions((await api.get<Question[]>('/skills/digital-literacy/questions')).data); if(user.role==='TRAINEE'){setAttempts((await api.get<Attempt[]>('/skills/digital-literacy/my-attempts')).data);}else{setAttempts((await api.get<Attempt[]>('/skills/digital-literacy/attempts')).data);}}catch(e:any){setError(e.response?.data?.detail||'Could not load digital literacy assessment');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function submit(){if(Object.keys(answers).length!==questions.length){setError('Please answer all questions before submitting.');return;}setSaving(true);setError('');try{const r=(await api.post<Result>('/skills/digital-literacy/attempts',{answers})).data;setResult(r);setAttempts((await api.get<Attempt[]>('/skills/digital-literacy/my-attempts')).data);}catch(e:any){setError(e.response?.data?.detail||'Could not submit assessment');}finally{setSaving(false);}}
 if(loading)return <section className="panel"><h2>Digital Literacy Assessment</h2><p className="muted">Loading assessment…</p></section>;
 if(user.role!=='TRAINEE')return <section className="panel"><div className="section-heading"><div><p className="eyebrow">SKILLS • DIGITAL LITERACY</p><h2>Digital Literacy Results</h2><p className="muted">Review assessment results within your role scope.</p></div><button className="secondary" onClick={load}>Refresh</button></div>{error&&<div className="error">{error}</div>}{!attempts.length?<div className="empty-state"><h3>No assessments completed</h3><p className="muted">Trainee digital literacy results will appear here after assessments are submitted.</p></div>:<div className="table-wrap"><table><thead><tr><th>Trainee</th><th>Score</th><th>Percentage</th><th>Level</th><th>Completed</th></tr></thead><tbody>{attempts.map(a=><tr key={a.id}><td><strong>{a.trainee_name}</strong><small>{a.trainee_email}</small></td><td>{a.score}/{a.total_questions}</td><td>{a.percentage}%</td><td><span className="status-badge">{a.level}</span></td><td>{new Date(a.completed_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</section>;
 return <section className="careers-shell"><div className="panel careers-hero"><div><p className="eyebrow">SKILLS • DIGITAL LITERACY</p><h2>Digital Literacy Assessment</h2><p className="muted">Assess practical digital safety, productivity and online-work skills. Your latest level is stored in your participant profile.</p></div><div className="career-stat"><strong>{attempts.length}</strong><span>attempts</span></div></div>{error&&<div className="error">{error}</div>}{result&&<div className="panel"><h3>Latest result</h3><div className="placement-summary"><div><strong>{result.percentage}%</strong><span>Score</span></div><div><strong>{result.level}</strong><span>Level</span></div><div><strong>{result.score}/{result.total_questions}</strong><span>Correct</span></div></div></div>}<div className="panel"><div className="section-heading"><div><h3>Assessment</h3><p className="muted">Choose one answer for each question.</p></div></div>{questions.map((q,i)=><div className="career-form" key={q.id}><h4>{i+1}. {q.question}</h4>{q.options.map((o,j)=><label key={o}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>setAnswers({...answers,[q.id]:j})}/>{o}</label>)}</div>)}<button className="primary" disabled={saving} onClick={submit}>{saving?'Submitting…':'Submit assessment'}</button></div>{attempts.length>0&&<div className="panel"><h3>Previous attempts</h3><div className="table-wrap"><table><thead><tr><th>Score</th><th>Level</th><th>Completed</th></tr></thead><tbody>{attempts.map(a=><tr key={a.id}><td>{a.percentage}% ({a.score}/{a.total_questions})</td><td>{a.level}</td><td>{new Date(a.completed_at).toLocaleString()}</td></tr>)}</tbody></table></div></div>}</section>;
}
