import { useEffect, useState } from 'react';
import { api } from '../training/api';

type User={id:number;full_name:string;email:string;role:string};
type Catalog={id:number;code:string;name:string;category:string;description?:string;active:boolean};
type Skill={id:number;skill_id:number;code:string;name:string;category:string;proficiency:number;proficiency_label:string;evidence_type:string;evidence_note?:string;updated_at:string};
type Gap={skill_id:number;code:string;name:string;category:string;current_proficiency:number;target_proficiency:number;gap:number};
type Passport={trainee_id:number;trainee_name:string;trainee_email:string;digital_literacy_level:string;skills:Skill[];skill_gaps:Gap[];total_skills:number;verified_skills:number};

const levelNames=['','Foundation','Basic','Working','Proficient','Advanced'];
export function SkillPassport({user}:{user:User}){
 const [passport,setPassport]=useState<Passport|null>(null); const [passports,setPassports]=useState<Passport[]>([]); const [catalog,setCatalog]=useState<Catalog[]>([]); const [selected,setSelected]=useState<number|null>(null); const [skillId,setSkillId]=useState(''); const [proficiency,setProficiency]=useState(3); const [evidenceNote,setEvidenceNote]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{setCatalog((await api.get<Catalog[]>('/skills/passport/catalog')).data); if(user.role==='TRAINEE') setPassport((await api.get<Passport>('/skills/passport/my')).data); else setPassports((await api.get<Passport[]>('/skills/passport')).data);}catch(e:any){setError(e.response?.data?.detail||'Could not load skill passport');}finally{setLoading(false);}}
 useEffect(()=>{load();},[user.role]);
 const current=passport || passports.find(p=>p.trainee_id===selected) || null;
 async function assign(){if(!selected||!skillId)return;setSaving(true);setError('');setMessage('');try{await api.post('/skills/passport/assign',{trainee_id:selected,skill_id:Number(skillId),proficiency,evidence_type:'TRAINER_VERIFIED',evidence_note:evidenceNote||undefined});setMessage('Skill passport updated.');setEvidenceNote('');setSkillId('');setProficiency(3);const fresh=(await api.get<Passport[]>(`/skills/passport`)).data;setPassports(fresh); }catch(e:any){setError(e.response?.data?.detail||'Could not update skill passport');}finally{setSaving(false);}}
 if(loading)return <section className="panel"><h2>Skill Passport</h2><p className="muted">Loading skills…</p></section>;
 return <section className="credentials-shell">
  <div className="panel credentials-hero"><div><p className="eyebrow">SKILLS • SKILLS-02</p><h2>Competency & Skill Passport</h2><p className="muted">A structured view of demonstrated cooperative, digital and professional skills, including current gaps to a working proficiency target.</p></div><div className="credential-count"><strong>{current?.total_skills||0}</strong><span>skills</span></div></div>
  {error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
  {user.role!=='TRAINEE'&&<div className="panel"><div className="section-heading"><div><h3>Trainee passports</h3><p className="muted">Select a trainee within your role scope to review or update their competencies.</p></div><button className="secondary" onClick={load}>Refresh</button></div><div className="career-form"><label>Trainee<select value={selected??''} onChange={e=>setSelected(e.target.value?Number(e.target.value):null)}><option value="">Select trainee</option>{passports.map(p=><option key={p.trainee_id} value={p.trainee_id}>{p.trainee_name} • {p.trainee_email}</option>)}</select></label></div></div>}
  {current&&<>
   <div className="credential-stats"><div className="panel"><strong>{current.total_skills}</strong><span>Skills recorded</span></div><div className="panel"><strong>{current.verified_skills}</strong><span>Verified / assessed</span></div><div className="panel"><strong>{current.skill_gaps.length}</strong><span>Skill gaps</span></div><div className="panel"><strong>{current.digital_literacy_level}</strong><span>Digital literacy</span></div></div>
   {user.role!=='TRAINEE'&&<div className="panel"><div className="section-heading"><div><h3>Update competency</h3><p className="muted">Record a trainer/admin verified proficiency from 1 to 5.</p></div></div><div className="form-row"><label>Skill<select value={skillId} onChange={e=>setSkillId(e.target.value)}><option value="">Select skill</option>{catalog.map(s=><option key={s.id} value={s.id}>{s.name} • {s.category}</option>)}</select></label><label>Proficiency<select value={proficiency} onChange={e=>setProficiency(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {levelNames[n]}</option>)}</select></label></div><label>Evidence note<textarea rows={2} value={evidenceNote} onChange={e=>setEvidenceNote(e.target.value)} placeholder="Observed during training / assessment / practical task"/></label><button className="primary" disabled={saving||!selected||!skillId} onClick={assign}>{saving?'Saving…':'Save competency'}</button></div>}
   <div className="panel"><div className="section-heading"><div><h3>{current.trainee_name}'s skill passport</h3><p className="muted">{current.trainee_email}</p></div></div>{!current.skills.length?<div className="empty-state"><h3>No skills recorded yet</h3><p className="muted">Verified skills will appear here as competencies are assessed.</p></div>:<div className="table-wrap"><table><thead><tr><th>Skill</th><th>Category</th><th>Proficiency</th><th>Evidence</th><th>Updated</th></tr></thead><tbody>{current.skills.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.code}</small></td><td>{s.category}</td><td><span className="status-badge">{s.proficiency}/5 • {s.proficiency_label}</span></td><td>{s.evidence_type}<small>{s.evidence_note||'No note'}</small></td><td>{new Date(s.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</div>
   <div className="panel"><div className="section-heading"><div><h3>Skill gaps</h3><p className="muted">Skills below the working proficiency target of 3 are surfaced for further training.</p></div></div>{!current.skill_gaps.length?<div className="empty">No current gaps against the working target.</div>:<div className="candidate-directory">{current.skill_gaps.map(g=><div className="candidate-card" key={g.skill_id}><div><strong>{g.name}</strong><span>{g.category}</span><small>Current: {g.current_proficiency?`${g.current_proficiency}/5`:'Not assessed'} • Target: {g.target_proficiency}/5</small></div><span className="status-badge">Gap {g.gap}</span></div>)}</div>}</div>
  </>}
  {!current&&<div className="panel empty-state"><h3>Select a trainee</h3><p className="muted">Choose a trainee above to view their competency passport.</p></div>}
 </section>;
}
