import { useEffect, useState } from 'react';
import { api } from '../training/api';

type User={id:number;full_name:string;email:string;role:string};
type Gap={skill_id:number;code:string;name:string;category:string;current_proficiency:number;target_proficiency:number;gap:number};
type CourseRec={course_id:number;course_code:string;title:string;category:string;level:string;delivery_mode:string;match_score:number;matched_skills:string[];reason:string};
type JobRec={job_id:number;title:string;organization_name:string;location:string;employment_type:string;match_score:number;matched_skills:string[];missing_skills:string[];reason:string};
type Recommendations={trainee_id:number;trainee_name:string;digital_literacy_level:string;skill_gaps:Gap[];learning_recommendations:CourseRec[];job_recommendations:JobRec[]};
type Passport={trainee_id:number;trainee_name:string;trainee_email:string};

export function SkillRecommendations({user}:{user:User}){
 const [data,setData]=useState<Recommendations|null>(null); const [passports,setPassports]=useState<Passport[]>([]); const [selected,setSelected]=useState<number|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function load(id?:number){setLoading(true);setError('');try{if(user.role==='TRAINEE'){setData((await api.get<Recommendations>('/skills/recommendations/my')).data);}else if(id){setData((await api.get<Recommendations>(`/skills/recommendations/${id}`)).data);}else{setPassports((await api.get<Passport[]>('/skills/passport')).data);}}catch(e:any){setError(e.response?.data?.detail||'Could not load skill recommendations');}finally{setLoading(false);}}
 useEffect(()=>{load();},[user.role]);
 if(loading)return <section className="panel"><h2>Skill Recommendations</h2><p className="muted">Building recommendations from your skill gaps…</p></section>;
 return <section className="credentials-shell">
  <div className="panel credentials-hero"><div><p className="eyebrow">SKILLS • SKILLS-03</p><h2>Skill Gap & Learning Recommendations</h2><p className="muted">Turn competency gaps into practical learning actions and employment opportunities using the NCCT training and careers catalogue.</p></div><div className="credential-count"><strong>{data?.skill_gaps.length||0}</strong><span>skill gaps</span></div></div>
  {error&&<div className="error">{error}</div>}
  {user.role!=='TRAINEE'&&<div className="panel"><div className="section-heading"><div><h3>Trainee recommendations</h3><p className="muted">Select a trainee within your existing Skill Passport scope.</p></div><button className="secondary" onClick={()=>load()}>Refresh</button></div><label>Trainee<select value={selected??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;setSelected(id);if(id)load(id);}}><option value="">Select trainee</option>{passports.map(p=><option key={p.trainee_id} value={p.trainee_id}>{p.trainee_name} • {p.trainee_email}</option>)}</select></label></div>}
  {!data?<div className="panel empty-state"><h3>Select a trainee</h3><p className="muted">Choose a trainee to generate skill-gap recommendations.</p></div>:<>
   <div className="credential-stats"><div className="panel"><strong>{data.skill_gaps.length}</strong><span>Skill gaps</span></div><div className="panel"><strong>{data.learning_recommendations.length}</strong><span>Learning actions</span></div><div className="panel"><strong>{data.job_recommendations.length}</strong><span>Job matches</span></div><div className="panel"><strong>{data.digital_literacy_level}</strong><span>Digital literacy</span></div></div>
   <div className="panel"><div className="section-heading"><div><h3>Priority skill gaps</h3><p className="muted">Working proficiency is the current target. Higher gaps should be addressed first.</p></div></div>{!data.skill_gaps.length?<div className="empty">No skill gaps detected.</div>:<div className="candidate-directory">{data.skill_gaps.slice().sort((a,b)=>b.gap-a.gap).map(g=><div className="candidate-card" key={g.skill_id}><div><strong>{g.name}</strong><span>{g.category}</span><small>Current: {g.current_proficiency?`${g.current_proficiency}/5`:'Not assessed'} • Target: {g.target_proficiency}/5</small></div><span className="status-badge">Gap {g.gap}</span></div>)}</div>}</div>
   <div className="panel"><div className="section-heading"><div><h3>Recommended learning</h3><p className="muted">Published NCCT courses are matched against the trainee's current skill gaps.</p></div></div>{!data.learning_recommendations.length?<div className="empty">No matching published courses found yet. Add or publish relevant courses in Training ERP.</div>:<div className="recommendation-grid">{data.learning_recommendations.map(r=><div className="recommendation-card" key={r.course_id}><div className="recommendation-score">{r.match_score}% match</div><strong>{r.title}</strong><span>{r.course_code} • {r.category}</span><small>{r.level} • {r.delivery_mode}</small><small>{r.reason}</small></div>)}</div>}</div>
   <div className="panel"><div className="section-heading"><div><h3>Employment opportunities</h3><p className="muted">Published jobs with skills related to the trainee's current profile and gaps.</p></div></div>{!data.job_recommendations.length?<div className="empty">No matching published jobs found yet.</div>:<div className="recommendation-grid">{data.job_recommendations.map(r=><div className="recommendation-card" key={r.job_id}><div className="recommendation-score">{r.match_score}% match</div><strong>{r.title}</strong><span>{r.organization_name}</span><small>{r.location} • {r.employment_type.replace('_',' ')}</small><small>{r.matched_skills.length?`Matched: ${r.matched_skills.join(', ')}`:'Profile match'}</small>{r.missing_skills.length>0&&<small>Build next: {r.missing_skills.join(', ')}</small>}</div>)}</div>}</div>
  </>}
 </section>;
}
